### ISSUE TITLE
获取用户信息问题

### ISSUE THREAD

**Issue by yk-795** [mafqla/imooc-api#2]
获取用户信息时，无论切换哪个用户，最终获得的用户信息都是super-admin的

**Comment by mafqla** [comment]
已修复

**Comment by yk-795** [comment]
现在是前端调用接口报500错误，服务器报错TypeError: Cannot read properties of null (reading 'id')

**Comment by mafqla** [comment]
我测试接口没有问题啊！

**Comment by mafqla** [comment]
![image](https://user-images.githubusercontent.com/57307446/184854017-7dd028d2-fa29-4918-b10a-7a95bdfe602d.png)

**Comment by mafqla** [comment]
> 现在是前端调用接口报500错误，服务器报错TypeError: Cannot read properties of null (reading 'id')

你有传进token吗？

**Comment by yk-795** [comment]
![image](https://user-images.githubusercontent.com/61232992/184864204-a4977174-0c58-4f7f-84b8-30bbaacf6d8c.png)
![image](https://user-images.githubusercontent.com/61232992/184864325-ac756ca5-5fe7-4272-8671-d11b5ae58f97.png)

**Comment by yk-795** [comment]
token已经传入了，但还是不行

**Comment by yk-795** [comment]
![image](https://user-images.githubusercontent.com/61232992/184865011-81bf80db-8447-4daf-8639-0d6cc001849b.png)

**Comment by yk-795** [comment]
![image](https://user-images.githubusercontent.com/61232992/184865773-58c948cd-7b74-4cc9-8f08-6ab2e999ca2b.png)
测试了一下接口，发现获取员工列表也是一样的问题报错

**Comment by yk-795** [comment]
![image](https://user-images.githubusercontent.com/61232992/184866964-92cc71d7-9cf5-424a-878f-93f453b32a14.png)

**Comment by mafqla** [comment]
> ![image](https://user-images.githubusercontent.com/61232992/184866964-92cc71d7-9cf5-424a-878f-93f453b32a14.png)

浪费我时间，你会不会发送token啊！自己百度去。看到你填token位置，我真的想笑，难怪你会500。我就应该在服务端，直接token拦截，让你一个请求都发不了

**Comment by mafqla** [comment]
> ![image](https://user-images.githubusercontent.com/61232992/184864204-a4977174-0c58-4f7f-84b8-30bbaacf6d8c.png) ![image](https://user-images.githubusercontent.com/61232992/184864325-ac756ca5-5fe7-4272-8671-d11b5ae58f97.png)

![image](https://user-images.githubusercontent.com/57307446/184872583-f10b94a7-56ec-42a9-8577-06c5d79ddf72.png)
看清楚，浪费我时间
